[versions]
agp = "8.4.1"
junit = "4.13.2"
junitVersion = "1.1.5"
volley = "1.2.1"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
googlemaps = "19.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "googlemaps" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

